<?php

$sortBy = (strtoupper($this->sorting) == 'ASC' || !in_array(strtoupper($this->sorting), ['ASC', 'DESC'])) ?
    'DESC' : 'ASC';

$linkVal = ($sortBy == 'DESC') ? '&darr;' : '&uarr;';

$link = "<a href='/main/allusers/?sort={$sortBy}'>Ages {$linkVal}</a>";


?>
<table border="1" cellspacing="1">
    <thead>
        <tr>
            <th>Id</th>
            <th>Mail</th>
            <th>Name</th>
            <th>Birthdate</th>
            <th><?=$link;?></th>
            <th>Adult</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->users)): ?>
            <?php foreach($this->users as $user): ?>
                <tr>
                    <td><?=$user['id'];?></td>
                    <td><?=$user['mail'];?></td>
                    <td><?=$user['first_name'];?></td>
                    <td><?=$user['birthdate'];?></td>
                    <td><?=$user['ages'];?></td>
                    <td><?=($user['ages'] > 18 ? 'Совершеннолетний' : 'Несовершеннолетний');?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif;?>
    </tbody>
</table>