<?php if (is_array($this->viewErrors) && count($this->viewErrors)): ?>
    <div style="color:red;padding:10px;">
        <?php foreach($this->viewErrors as $value): ?>
            <div>• <?=$value;?></div>
        <?php endforeach;?>
    </div>
<?php endif; ?>
<?php if (is_array($this->successMessages) && count($this->successMessages)): ?>
    <div style="color:green;padding:10px;">
        <?php foreach($this->successMessages as $value): ?>
            <div>• <?=$value;?></div>
        <?php endforeach;?>
    </div>
<?php endif; ?>

<form method="POST" enctype="multipart/form-data">
    <table cellpadding="3">
        <thead>
            <tr>
                <td><b>Photos:</b> (May be multiple)</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input type="file" name="photo[]" multiple="multiple" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td><br><input type="submit" value=">>> Upload <<<" /></td>
            </tr>
        </tfoot>
    </table>
</form>

<script>
    $(document).ready(function() {
        $('form').on('change', 'input[name^=photo]', function(event) {
            event.preventDefault();
            if ($('input[name^=photo]:last').val() != '') {
                let newButton = '<tr><td><input type="file" name="photo[]" multiple="multiple"></td></tr>';
                $(this).parent().parent().parent().append(newButton);
            }
        });
    })
</script>