<?php if (is_array($this->viewErrors) && count($this->viewErrors)): ?>
    <div style="color:red">
        <?php foreach($this->viewErrors as $value): ?>
            <div><?=$value;?></div>
        <?php endforeach;?>
    </div>
<?php endif; ?>

<form method="POST">
    <table cellpadding="3">
        <tr>
            <td><label><b>Mail:</b><br><input type="text" name="mail" maxlength="50" placeholder="Your mail" value="<?=$this->mail;?>" /></label></td>
            <td><label><b>Password:</b><br><input type="password" name="password" maxlength="255" placeholder="Password" value="" /></label></td>
            <td><label><br><input type="checkbox" name="remember" value="1" />Remember me</label></td>
            <td><label><br><input type="submit" value="Sign in" /></label></td>
            <input type="hidden" value="1" name="from_login" />
        </tr>
    </table>
</form>