<!-- Main Header & Footer -->
<?php
/** @var \core\models\CurrentUser $curUser */
$curUser = $this->curUser;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$this->pageTitle;?></title>
    <script src="//code.jquery.com/jquery-1.8.2.min.js"></script>
</head>
<body>
<h1><?=$this->pageTitle;?></h1>
<a href="/">Main</a> |
<?php if (!$this->curUser->isLogged()): ?>
    <a href="/login">Sign in</a> | <a href="/register">Sign up</a> |
<?php else: ?>
    <a href="/logout">Logout</a> | <a href="/profile">My profile</a> | <a href="/main/allusers">All users</a> | <a href="/photo/upload">Upload a photo</a> |
<?php endif; ?>
<a href="/not_found">404 Page</a><hr>
<?php
    include $this->pathToTemplate;
?>
</body>
</html>